### ISSUE TITLE
Repository clean up

### ISSUE THREAD

**Issue by e8kor** [myermolenko/MAT#5]
Please update **.gitignore** file and remove folders and files from repository like : **.iml**, **.idea**
This tip is very useful for future git usage, since its done contributors will not be able to commit their IntelliJ Idea specific settings and override them for someone other.
Useful link: 
* [Accidentally committed .idea directory files into git](http://stackoverflow.com/questions/11124053/accidentally-committed-idea-directory-files-into-git)
* [Remove a file from a Git repository without deleting it from the local filesystem](http://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste?lq=1)

**Comment by Alex-Korniichuk** [comment]
I have removed all maven libraries from .idea folder and they were removed from local system. How can I revert to previous commit where we didn't have all this mess?

**Comment by Alex-Korniichuk** [comment]
Can I roll back to normal state of project by using:
git reset --hard <commit>?

**Comment by Alex-Korniichuk** [comment]
Decided to use:

Rename your current master branch:

git branch -m crazy experiment

Check out your good commit:

git checkout c2e7af2b51

Make your new master branch here:

git checkout -b master

Now you still have your crazy experiment around if you want to look at it later, but your master branch is back at your last known good point, ready to be added to. If you really want to throw away your experiment, you can use:

git branch -D crazyexperiment

**Comment by e8kor** [comment]
@Alex-Korniichuk I think that you have multiple ways to resolve this issue:
* one is recreate project from scratch and be sure that there is no trash files in repo and **.gitignore** covers all of them (quite naive one).
* update .gitignore, commit file, remove files from git, commit, check in console(or IDEA) that this files not under version control system, push changes, github.com will always display every file that it has in branch.

be sure that files will not appear back in repository after some feature branch merge, this actually requires only attention of person who is going to merge changes.

Steps that you choose for reverting branch looks very good to me.
